// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]" | "/[locale]/about" | "/[locale]/apps" | "/[locale]/apps/[slug]" | "/[locale]/apps/[slug]/releases" | "/[locale]/apps/[slug]/thanks" | "/[locale]/blog" | "/[locale]/blog/[slug]" | "/[locale]/blog/tag/[slug]" | "/[locale]/contact" | "/[locale]/founding" | "/[locale]/privacy" | "/[locale]/services" | "/[locale]/solutions/ai-agents" | "/[locale]/solutions/azure" | "/[locale]/terms" | "/admin" | "/privacy" | "/stats" | "/terms"
type AppRouteHandlerRoutes = "/api/admin/files" | "/api/admin/files/[...path]" | "/api/stats"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]" | "/[locale]/about" | "/[locale]/apps" | "/[locale]/blog/[slug]" | "/[locale]/blog/tag/[slug]" | "/[locale]/contact" | "/[locale]/founding" | "/[locale]/privacy" | "/[locale]/services" | "/[locale]/solutions/ai-agents" | "/[locale]/solutions/azure" | "/[locale]/terms" | "/admin" | "/stats"
type RedirectRoutes = "/en/blog/vec-push-vs-with-capacity-performance-duplicate" | "/fr/blog/box-slice-vs-vec-differences-fr" | "/fr/blog/collect-method-rust-fr" | "/fr/blog/efficient-duplicate-removal-vec-fr" | "/fr/blog/flatten-vec-iterators-performance-fr" | "/fr/blog/iter-methods-rust-fr" | "/fr/blog/vec-drain-vs-truncate-clear-fr" | "/fr/blog/vec-new-vs-with-capacity-fr" | "/fr/blog/vec-push-vs-with-capacity-performance-duplicate" | "/fr/blog/vec-push-vs-with-capacity-performance-duplicate-fr" | "/fr/blog/vec-retain-vs-filter-collect-fr"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/apps": { "locale": string; }
  "/[locale]/apps/[slug]": { "locale": string; "slug": string; }
  "/[locale]/apps/[slug]/releases": { "locale": string; "slug": string; }
  "/[locale]/apps/[slug]/thanks": { "locale": string; "slug": string; }
  "/[locale]/blog": { "locale": string; }
  "/[locale]/blog/[slug]": { "locale": string; "slug": string; }
  "/[locale]/blog/tag/[slug]": { "locale": string; "slug": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/founding": { "locale": string; }
  "/[locale]/privacy": { "locale": string; }
  "/[locale]/services": { "locale": string; }
  "/[locale]/solutions/ai-agents": { "locale": string; }
  "/[locale]/solutions/azure": { "locale": string; }
  "/[locale]/terms": { "locale": string; }
  "/admin": {}
  "/api/admin/files": {}
  "/api/admin/files/[...path]": { "path": string[]; }
  "/api/stats": {}
  "/en/blog/vec-push-vs-with-capacity-performance-duplicate": {}
  "/fr/blog/box-slice-vs-vec-differences-fr": {}
  "/fr/blog/collect-method-rust-fr": {}
  "/fr/blog/efficient-duplicate-removal-vec-fr": {}
  "/fr/blog/flatten-vec-iterators-performance-fr": {}
  "/fr/blog/iter-methods-rust-fr": {}
  "/fr/blog/vec-drain-vs-truncate-clear-fr": {}
  "/fr/blog/vec-new-vs-with-capacity-fr": {}
  "/fr/blog/vec-push-vs-with-capacity-performance-duplicate": {}
  "/fr/blog/vec-push-vs-with-capacity-performance-duplicate-fr": {}
  "/fr/blog/vec-retain-vs-filter-collect-fr": {}
  "/privacy": {}
  "/stats": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
  "/[locale]/about": never
  "/[locale]/apps": never
  "/[locale]/blog/[slug]": never
  "/[locale]/blog/tag/[slug]": never
  "/[locale]/contact": never
  "/[locale]/founding": never
  "/[locale]/privacy": never
  "/[locale]/services": never
  "/[locale]/solutions/ai-agents": never
  "/[locale]/solutions/azure": never
  "/[locale]/terms": never
  "/admin": never
  "/stats": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
