// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/[locale]/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/about">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/apps/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/apps/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/apps/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/apps/[slug]/releases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/apps/[slug]/releases">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/apps/[slug]/releases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/apps/[slug]/thanks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/apps/[slug]/thanks">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/apps/[slug]/thanks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/apps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/apps">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/apps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/tag/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/tag/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/tag/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/founding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/founding">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/founding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/services">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/solutions/ai-agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/ai-agents">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/solutions/ai-agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/solutions/azure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/azure">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/solutions/azure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/files/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/files/[...path]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/files/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/files">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/[locale]/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/about">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/apps/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/apps">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/apps/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/tag/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/blog/tag/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/tag/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/founding/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/founding">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/founding/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/privacy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/privacy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/services/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/services">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/services/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/solutions/ai-agents/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/solutions/ai-agents">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/solutions/ai-agents/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/solutions/azure/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/solutions/azure">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/solutions/azure/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/terms/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/terms/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/stats/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/stats/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
