# Simplified Publishing Configuration
# File: config/publishing.yaml

# Just a simple list of languages to publish
languages:
  - en
  - fr

# Basic publishing settings
publishing:
  publishTime: "09:00"
  timezone: "Europe/Zurich"
  skipWeekends: true
  maxPerDay: 1  # Total articles per day across all languages

# Logging
logging:
  level: "info"
  file: "/var/log/blog-publishing.log"
